dist: xenial

os:
- linux

language: go

go:
- "1.13.x"
- tip

matrix:
  allow_failures:
  - go: tip

env:
  GOLANGCI_RELEASE="v1.18.0"

before_install:
- GO111MODULE=off go get github.com/mattn/goveralls
- curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLANGCI_RELEASE}

script:
- make test
- make lint
- goveralls -service=travis-ci
